### ISSUE TITLE
Tarea1_3101463

### ISSUE THREAD

**Issue by dresvicom07** [dersteppenwolf/cartografia_web#10]
Buen día, el link de la tarea 1
https://github.com/dresvicom07/cartoweb/blob/master/Tarea1/Tarea1_3101463.md

**Comment by dersteppenwolf** [comment]
Comentarios

No entendí el objetivo de simbolizar las líneas de la simbología  ni tampoco porque adicionar el sombreado

En el segundo, los datos parecieran provenir de acá? https://www.datos.gov.co/Inclusi-n-Social-y-Reconciliaci-n/Eventos-Minas-Antipersonal-en-Colombia/sgp4-3e6k
El mapa de fondo genera mucho ruido debido a la cantidad de colores que tiene. 
Para los mapas temáticos sugeriría utilizar mapas base más simples. Ejemplo https://carto.com/blog/getting-to-know-positron-and-dark-matter/
