### ISSUE TITLE
Tarea 1 - 3101470

### ISSUE THREAD

**Issue by jsortegac1** [dersteppenwolf/cartografia_web#13]
https://github.com/jsortegac1/Sebasti-n-Ortega/blob/master/Tarea1.md

**Comment by dersteppenwolf** [comment]
Entregó tarde
Debe tener cuidado con la selección de los métodos de clasificación
Utilizó una variable contínua para representarla como categórica lo cual es un error.
ver https://johnguerra.co/lectures/visualAnalytics_fall2019/02_What_Why_How/#/
