### ISSUE TITLE
MAPGuide

### ISSUE THREAD

**Issue by Hectorcas85** [dersteppenwolf/cartografia_web#14]
Saludos Profe

Mi siguiente inquietud, es saber si posee información acerca del aplicativo MapGuide, tutoriales, manuales para implementar al proyecto.

Muchas gracias.

**Comment by dersteppenwolf** [comment]
Según lo evidenciado, la herramienta MapGuide ya se encuentra bastante desactualizada, casi no hay documentación, etc.

En su lugar recomendaría utilizar geoserver para publicar los servicios geográficos y alguna herramienta ya existente para la interfaz gráfica del visor.


La siguiente herramienta permite configurar un visor para servicios geográficos OGC y Arcgis Server
https://terria.io/

este es el demo 
https://map.terria.io/

Tendía que mirar si funciona en windows.  (Únicamente la he utilizado en linux)

Ya otras cosas más avanzadas requerirían programación o algún tipo de pago.
Ejemplos
https://live.osgeo.org/archive/10.5/es/overview/mapfish_overview.html
https://mapstore.geo-solutions.it/mapstore/#/
https://cmv.io/
https://www.giscloud.com/apps/map-viewer
