### ISSUE TITLE
Pregunta

### ISSUE THREAD

**Issue by dresvicom07** [dersteppenwolf/cartografia_web#17]
Estoy intentando crear una capa por medio de un intersects con los shape cargados a la base de datos y tener solo un shape de puntos con la información de las amenzas y los departamentos, pero no he podido hacer que la consulta me genere lo que quiero. Podria colaborarme con la ayuda a este paso?. le envio lo que intenté y genera una geomatria vacia. 

Gracias!

SELECT m.geom
FROM u7_inst_minera_wgs84 m, u7_amenzasismica_wgs84 a, departamentos_u5 g
WHERE st_intersects(m.geom, a.geom)=true

**Comment by dersteppenwolf** [comment]
Buen día
varias cosas,

- ya validó que las geometrías a intersectar tienen el mismo sistema de coordenadas?
-  lo que desea es adicionar todos los polígonos de  dos capas diferentes en una sola tabla?  cual es la interpretación de eso?
- en el query del ejemplo en el from hay 3 tablas pero en el where solo utiliza dos y al final en el select solo retorna una geometría, pero en realidad no se entiende para qué el intersect.

saludos
