### ISSUE TITLE
Pregunta_

### ISSUE THREAD

**Issue by jenny-saray** [dersteppenwolf/cartografia_web#18]
Buen dia profesor,

me sale el siguiente error al momento de conectar postGIS con geoserver:

![img1](Imagenes/Consulta.PNG)

![img1](Consultas/Consulta.PNG)

*No se que pasa que no muestra las imagen del pantallazo, la puedes consultar en mi carpeta de imagenes por favor

**Comment by dersteppenwolf** [comment]
es esta imagen?
https://github.com/jenny-saray/Jenny_Saray/blob/master/Imagenes/Consulta.PNG

pareciera que tienes mal la conexión en alguno de los parámetros

acabo de validar la conexión al servidor desde mi equipo y funciona bien.

o tal vez fue lo mismo que me pasó en el mac (el error de qgis 3.10 con postgresql 12)

qué versión tienes instalada de qgis?
acá me funcionó sin problema con la Versión 3.4.14 LTR

**Comment by jenny-saray** [comment]
Si señor esa esa la imagen y caí en cuenta que obvio no se iba a subir porque esta es en mi repositorio :(

Según el pantallazo identificas si hay algún parámetro que este ingresando mal? tome tan cual los que nos enviaste por correo.

Tengo Qgis 3.10

**Hay otra opción de subir las capas que no sea Qgis?**

**Comment by dersteppenwolf** [comment]
la Versión 3.4.14 LTR no genera problemas con postgresql 12

**Comment by dersteppenwolf** [comment]
Hay otras formas de cargar los datos (ejm. gdal)
pero pues qgis es la más fácil

ejm cargar csv a postgis con gdal:

>     ogr2ogr -f PostgreSQL PG:"host=localhost user=miusuario dbname=mibd password=mipwd" \
>        miarchivo.csv -progress    -lco OVERWRITE=yes -nln mi_tabla_en_postgresql
