### ISSUE TITLE
TAREA 1 - 3101385

### ISSUE THREAD

**Issue by carlosocampo75** [dersteppenwolf/cartografia_web#20]
Buena Tarde Profesor, por fin me funciono el QGIS, Le envío la tarea con fines académicos.

https://github.com/carlosocampo75/PRUEBA/blob/master/Tarea%201%20-%203101385.md

**Comment by dersteppenwolf** [comment]
Entregó tarde.
Logró utilizar qgis para representar la simbología del tema seleccionado.
Como tal no creó mapas temáticos
http://www.geol-amu.org/notes/be1b-4-6b.htm
