### ISSUE TITLE
TAREA 2 - 3101462

### ISSUE THREAD

**Issue by Hectorcas85** [dersteppenwolf/cartografia_web#21]
https://github.com/Hectorcas85/cartowebhector/blob/master/Tarea%20_2/tarea_02.md

**Comment by dersteppenwolf** [comment]
No implementó simbología en CSS
No especifica la forma en que creó la clasificación para el conteo por departamento. De la misma forma, la rampa de colores utilizada se podría mejorar.  (para qué el color rojo? ) Sugeriría una escala secuencial
El geoprocesamiento realizado con postgis es muy básico para lo esperado al final de la especialización.
