### ISSUE TITLE
Ayuda Google Earth Engine

### ISSUE THREAD

**Issue by dresvicom07** [dersteppenwolf/cartografia_web#22]
Profe le envio un pequeño código para q vea q el clip no me funciona (para el corte puede subir cualquier shp)

// llamar la Coleccion

var IMGsentinel = ee.ImageCollection('COPERNICUS/S2')
                  .filterDate('2019-01-01', '2019-12-01')  
                  .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', 20))
                  .filterBounds(geometry);
var corte = IMGsentinel.clip(table);
//print(IMGsentinel);
Map.addLayer(table,{},'AOI');
Map.addLayer(geometry,{},'geom');
Map.addLayer(IMGsentinel,{max:10000, min:0, bands:['B11','B8','B4']},'IMGsentinel');
Map.setCenter(table,{},10);
var sorteo = IMGsentinel.sort('CLOUDY_PIXEL_PERCENTAGE');
var sentinel2 =ee.Image(sorteo.first());

Map.addLayer(sentinel2,{max:10000, min:0, bands:['B11','B8','B4']}, 'imagensincloud');

**Comment by dersteppenwolf** [comment]
Buen día
no entiendo
lo que quiere bajar es todas las imágenes que estén dentro de un área?
porque como tal en el código que envía no le está aplicando ningún procesamiento a las imágenes
tenga en cuenta que Map.addLayer lo único que hace es mostrarla en el visor de ejemplo
el ejemplo típico es el que le mostré
https://gist.github.com/dersteppenwolf/8313aee1ea387b7489c52aabbf201021
