### ISSUE TITLE
TAREA 2 - 3101463

### ISSUE THREAD

**Issue by dresvicom07** [dersteppenwolf/cartografia_web#23]
Buen día, adjunto link con la tarea 2

https://github.com/dresvicom07/cartoweb/blob/master/Tarea2/TAREA%202%20-%203101463.md

**Comment by dersteppenwolf** [comment]
No implementó simbología en CSS

El geoprocesamiento realizado con postgis es muy básico para lo esperado al final de la especialización.

Representó los departamentos como variable categórica. Son demasiadas categorías cuando al final pareciera que lo único que se quiere mostrar el el límite.

No especifica cual es el criterio utilizado para la selección de la simbología de puntos. (hexagon?)

No especifica cual es el criterio utilizado para la selección de la simbología de amenazas. 

No nombró todos los objetos creados con el prefijo solicitado.
