### ISSUE TITLE
Tarea 2 3101418

### ISSUE THREAD

**Issue by wilsonpc-geomatica** [dersteppenwolf/cartografia_web#24]
Buenas noches profesor, anexo la tarea 2

https://github.com/wilsonpc-geomatica/publicacionweb/blob/master/Taller2_3101418.md

**Comment by dersteppenwolf** [comment]
La simbología implementada en CSS es muy básica

No evidencia la realización de geoprocesamiento utilizando postgis.

Según el documento, representó las localidades como variable categórica. Son demasiadas categorías cuando al final pareciera que lo único que se quisiera es mostrar el límite.  El mapa web enviado no refleja la simbología definida para localidades.

![Captura de Pantalla 2019-12-15 a la(s) 06 53 04](https://user-images.githubusercontent.com/110606/70862226-98fa6400-1f07-11ea-894d-52aa7e3370b2.png)

No especifica cual es el criterio utilizado para la selección de la simbología de puntos y líneas
