### ISSUE TITLE
TAREA 2 - 3101385

### ISSUE THREAD

**Issue by carlosocampo75** [dersteppenwolf/cartografia_web#25]
Buena noche profeso, en el siguiente link dejo la tarea número 2

https://github.com/carlosocampo75/PRUEBA/blob/master/Tarea%202%20-%203101385.md

**Comment by dersteppenwolf** [comment]
No explica la utilidad de aplicar servicios web OGC a la resolución del problema según lo solicitado en el enunciado del ejercicio

El sistema de referencia utilizado para la carga de información es un poco extraño
(EPSG:404000) lo cual genera problemas al momento de visualizar.  Por qué ese sistema y no uno más común como WGS84, magna sirgas, web mercator, etc?

  ![Captura de Pantalla 2019-12-15 a la(s) 06 58 58](https://user-images.githubusercontent.com/110606/70862291-6e5cdb00-1f08-11ea-90ef-bf9b78d03c5a.png)

![Captura de Pantalla 2019-12-15 a la(s) 07 04 57](https://user-images.githubusercontent.com/110606/70862342-3e620780-1f09-11ea-9d23-96528e958562.png)


No evidencia la realización de geoprocesamiento utilizando postgis.

La simbología generada es muy básica

No evidencia la implementación de simbología utilizando CSS
