### ISSUE TITLE
Tarea2.md - 3101464

### ISSUE THREAD

**Issue by amezquita1** [dersteppenwolf/cartografia_web#26]
https://github.com/amezquita1/Cartografia-web/blob/master/tarea2.md

**Comment by dersteppenwolf** [comment]
Si lo que se quería representar era la "concentración de establecimientos de comercio como restaurantes y bares en la ciudad de Bogotá "  probablemente hubiera podido seleccionar otro tipo de mapa como por ejemplo clasificar las localidades por la cantidad de establecimientos o implementar un mapa de densidad de puntos (en caso que fueran demasiados datos).
Ejemplos https://carto.com/blog/popular-thematic-map-types-techniques-spatial-data/ 

El geoprocesamiento realizado con postgis es muy básico para lo esperado al final de la especialización.

No nombró los elementos creados con el prefijo asignado.  (El objetivo del prefijo es poder ubicar rápidamente los elementos en el geoserver). 

La simbología publicada es muy básica tanto en SLD como en cSS. 
Para el SLD pudo haber aprovechado más las funcionalidades que ofrece qgis al respecto.

Respecto a:

> Sin embargo no logre encontrar la forma de visualizar la zona de la capa deseada al momento de abrir el mapa en la web, pues la zona de interés es la ciudad de Bogotá, pero al contar con la capa de municipios de Colombia, el mapa abre la totalidad de la extensión del país, teniendo que ampliar este mapa hasta la zona de Bogotá.

Para el zoom a la zona de interés pudo utilizar la configuración de límites del grupo de capa. 

Ejemplo:
Encontrar el bbox de interés utilizando https://boundingbox.klokantech.com/
![Captura de Pantalla 2019-12-15 a la(s) 07 30 10](https://user-images.githubusercontent.com/110606/70862633-bf6ece00-1f0c-11ea-964c-9e2feb390cac.png)

Configurar los límites del grupo de capas en geoserver:
![Captura de Pantalla 2019-12-15 a la(s) 07 17 22](https://user-images.githubusercontent.com/110606/70862644-d2819e00-1f0c-11ea-9fac-2fef9640d93a.png)


Resultado:
http://34.83.176.208:18080/geoserver/wms?service=WMS&version=1.1.0&request=GetMap&layers=u0_zoom_bogota&bbox=-74.356325%2C4.371391%2C-73.88372%2C4.929162&width=650&height=768&srs=EPSG%3A4326&format=application/openlayers
![Captura de Pantalla 2019-12-15 a la(s) 07 31 52](https://user-images.githubusercontent.com/110606/70862657-fc3ac500-1f0c-11ea-85c6-e5e962ede447.png)

Vista en qgis:
![Captura de Pantalla 2019-12-15 a la(s) 07 34 23](https://user-images.githubusercontent.com/110606/70862688-59cf1180-1f0d-11ea-9b03-bb2256afb22b.png)
