### ISSUE TITLE
Tarea2-3101470

### ISSUE THREAD

**Issue by jsortegac1** [dersteppenwolf/cartografia_web#28]
https://github.com/jsortegac1/Sebasti-n-Ortega/blob/master/Tarea2.md

**Comment by dersteppenwolf** [comment]
Sugeriría mejor utilizar fuentes de datos oficiales de colombia (ejm. https://www.datos.gov.co/  ) en lugar de sitios desde donde no es clara la procedencia como  https://sites.google.com/site/seriescol/shapes


No nombró los elementos creados con el prefijo asignado.  (El objetivo del prefijo es poder ubicar rápidamente los elementos en el geoserver). 


El geoprocesamiento realizado con postgis es muy básico para lo esperado al final de la especialización.

No son claros los criterios utilizados para seleccionar la simbología utilizada.

La simbología publicada es muy básica . 




Respecto a :

> Durante el proceso se presentaron inconvenientes en la ejecución de la consulta en postgis, puesto que inicialmente se quería intersectar la capa de fallas geológicas con municipios y departamentos, no obstante, al momento de ejecutar la consulta tardaba demasiado tiempo y no mostraba resultados. Por tal motivo, se optó por hacer la intersección entre fallas geológicas y departamentos, proceso que también demoro bastante tiempo.

Probablemente la demora se deba a que en la consulta enviada como ejemplo 
![Captura de Pantalla 2019-12-15 a la(s) 07 43 20](https://user-images.githubusercontent.com/110606/70862767-98b19700-1f0e-11ea-84ec-80231e8886a7.png)
hace un proceso de transformación de coordenadas al vuelo lo que impide que el motor pueda aprovechar el uso de los índices espaciales.
En esos casos , además de la creación de los índices espaciales, lo que sugiero es que todas las geometrías a utilizar en el procesamiento estén almacenadas previamente en el mismo sistema de coordenadas.
