### ISSUE TITLE
Tarea 2_3101473

### ISSUE THREAD

**Issue by heilyr** [dersteppenwolf/cartografia_web#30]
https://github.com/heilyr/Cartografia-web/blob/master/Taller2HR.md

**Comment by dersteppenwolf** [comment]
El problema planteado es muy simple. No es claro como aplica la cartografía / simbología para la resolución del problema

No nombró los elementos creados con el prefijo asignado.  (El objetivo del prefijo es poder ubicar rápidamente los elementos en el geoserver). 

El ejercicio solicitaba la creación de  geoprocesamiento con postgis en el servidor de la clase  pero se adjuntó en su lugar procesos realizados con oracle spatial en máquinas diferentes en las cuales no se puede validar el proceso.

La simbología creada es muy básica.

No creó simbología CSS

No creó grupo de capas
