### ISSUE TITLE
Tarea3_3101418_3101385

### ISSUE THREAD

**Issue by wilsonpc-geomatica** [dersteppenwolf/cartografia_web#31]
Buenas noches profesor anexamos la tarea 3.

https://github.com/wilsonpc-geomatica/publicacionweb/blob/master/Tarea3_3101418_3101385.md

**Comment by dersteppenwolf** [comment]
Se esperaba que se aplicara algún tipo de análisis espacial aplicado al problema.
Según el ejercicio entregado, no se evidencia la ejecución de análisis espacial. (Valía que  fuera en postgis, model builder, etc)

Respecto a

> La ventaja principal de este tipo de software es que es de facil uso, muy estable, hay garantia de que se podrá publicar y difundir.

> La principal dificultad para la elaboracion del presente trabajo es el corto tiempo para la elaboración.

Efectivamente la facilidad de uso es un factor a favor al momento de implementar aplicaciones / visores en poco tiempo.  En ese orden de ideas se esperaba la realización de ejercicios de mayor complejidad  por ejemplo mezclando herramientas de diferentes proveedores, personalizando mapas base, aplicando análisis espaciales, etc.
