### ISSUE TITLE
Tarea 3 - 3101462 - 3101463

### ISSUE THREAD

**Issue by Hectorcas85** [dersteppenwolf/cartografia_web#32]
Adjuntamos desarrollo de la tarea 3

https://github.com/Hectorcas85/cartowebhector/blob/master/Tarea_3/tarea_03.md

**Comment by dersteppenwolf** [comment]
Se encontraron varios errores ("horrores") de ortografía en el texto.

Se esperaba que se aplicara algún tipo de análisis espacial aplicado al problema.
Según el ejercicio entregado, no se evidencia la ejecución de análisis espacial. (Valía que  fuera en postgis, model builder, etc)

El ejercicio entregado realmente no le saca provecho a la información geográfica. Simplemente se muestra un mapa base, pero pues en realidad de los eventos de catástrofes volcánicas  no se ve mayor cosa

La facilidad de uso de la herramienta seleccionada es un factor a favor al momento de implementar aplicaciones / visores en poco tiempo.  En ese orden de ideas,  se esperaba la realización de ejercicios de mayor complejidad  por ejemplo mezclando herramientas de diferentes proveedores, personalizando mapas base, aplicando análisis espaciales, etc.

Por último, el ejercicio era para grupos de dos, pero pues en realidad crear  un story map simple como el presentado no representa el esfuerzo esperado.
