### ISSUE TITLE
taller 3_3101473

### ISSUE THREAD

**Issue by heilyr** [dersteppenwolf/cartografia_web#33]
https://github.com/heilyr/Cartografia-web/blob/master/Taller3.md

**Comment by dersteppenwolf** [comment]
Se esperaba que se aplicara algún tipo de análisis espacial aplicado al problema.
Según el ejercicio entregado, no se evidencia la ejecución de análisis espacial. (Valía que  fuera en postgis, model builder, etc)

La facilidad de uso de la herramienta seleccionada es un factor a favor al momento de implementar aplicaciones / visores en poco tiempo.  En ese orden de ideas,  se esperaba la realización de ejercicios de mayor complejidad  por ejemplo mezclando herramientas de diferentes proveedores, personalizando mapas base, aplicando análisis espaciales, etc.
