### ISSUE TITLE
Tarea 3 - 3101464 - 3101470

### ISSUE THREAD

**Issue by amezquita1** [dersteppenwolf/cartografia_web#34]
https://github.com/amezquita1/Cartografia-web/blob/master/Tarea3.md

Andres Felipe Amezquita Sanchez
John Sebastian Ortega Cortes

**Comment by dersteppenwolf** [comment]
Quedó bien documentado el paso a paso.  (Esto es útil también para el caso que alguien quisiera replicar el procedimiento).

Válido el join entre archivos diferentes pero se esperaba que se aplicara algún tipo de análisis espacial aplicado al problema. Según el ejercicio entregado, no se evidencia la ejecución de análisis espacial. (Valía que  fuera en postgis, model builder, etc).  

Válida la personalización de la herramienta aprovechando las posibilidades de interactividad (ejm. popups, categorización, rampas de color).

La facilidad de uso de la herramienta seleccionada es un factor a favor al momento de implementar aplicaciones / visores en poco tiempo.  En ese orden de ideas,  se esperaba la realización de ejercicios de mayor complejidad  por ejemplo mezclando herramientas de diferentes proveedores, personalizando mapas base, aplicando análisis espaciales, etc.
