### ISSUE TITLE
Pregunta

### ISSUE THREAD

**Issue by dresvicom07** [dersteppenwolf/cartografia_web#5]
Buenas tardes.

Tengo una consulta, cuando le doy "upload data" en qgis cloud, una de las capas me genera el siguiente mensaje de error y no me deja publicar:

missing data for column "direccion"
CONTEXT:  COPY cicloparqueaderos_certificados, line 17: "116	01040000204e120000010000000101000000d887fc00528352c080d570c925b51240	485	117	City Parking kr 15 ..."

Traceback (most recent call last):
  File "C:/Users/Andres/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgiscloud\qgiscloudplugindialog.py", line 975, in upload_data
    self.data_upload.upload(self.db_connections.db(unicode(db_name)), data_sources_items, unicode(self.maxSize))
  File "C:/Users/Andres/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgiscloud\data_upload.py", line 284, in upload
    raise RuntimeError(str(messages))
RuntimeError: missing data for column "direccion"
CONTEXT:  COPY cicloparqueaderos_certificados, line 17: "116	01040000204e120000010000000101000000d887fc00528352c080d570c925b51240	485	117	City Parking kr 15 ..."

Que solución tiene. Gracias!

**Comment by dersteppenwolf** [comment]
Buen día, 
según el error pareciera que existe algún tipo de error de las geometrías.
Sugeriría reparar las    geometrías y volver intentar la carga

Para reparar geometrías con qgis:
https://docs.qgis.org/3.4/en/docs/user_manual/plugins/core_plugins/plugins_geometry_checker.html
https://gis.stackexchange.com/questions/289629/finding-invalid-geometry-using-qgis

Con arcgis:
http://desktop.arcgis.com/en/arcmap/latest/tools/data-management-toolbox/repair-geometry.htm 


saludos
