### ISSUE TITLE
Tarea2_3101489

### ISSUE THREAD

**Issue by mfmojicab** [dersteppenwolf/cartografia_web#52]
### Adjunto el link de la tarea 2. 

https://github.com/mfmojicab/mafe_clase_cartoweb/tree/master/Tarea_2_3101489

https://github.com/mfmojicab/mafe_clase_cartoweb/blob/master/Tarea_2_3101489/Readme.md

**Comment by dersteppenwolf** [comment]
Revisado
Muchas gracias
