### ISSUE TITLE
Tarea 1 - 3101462

### ISSUE THREAD

**Issue by Hectorcas85** [dersteppenwolf/cartografia_web#6]
https://github.com/Hectorcas85/cartowebhector/blob/master/Taller_1/taller_01.md

**Comment by dersteppenwolf** [comment]
Comentarios:

Faltó explicar mejor porque considera mejor un método de clasificación en comparación al otro.

Faltó explicar la razón por la cual utilizó la rampa de colores seleccionada.

Faltó comentar "Ventajas / desventajas / dificultades / diferencias encontradas al utilizar QGIS para el desarrollo del ejercicio" 

Me quedó la duda , cómo supo que los atributos como  "Exportacio " correspondían a un año específico?  en ningún lado de la metadata encontré la explicación precisa.
(ese usualmente es un problema común de los datos abiertos que publican en los diferentes portales en donde  a las entidades "se les olvida" documentar los conjuntos de datos de forma correcta.
