### ISSUE TITLE
Tarea 1_3101473

### ISSUE THREAD

**Issue by heilyr** [dersteppenwolf/cartografia_web#7]
https://github.com/heilyr/Cartografia-web/blob/master/Tarea1.md

**Comment by dersteppenwolf** [comment]
Comentarios:

únicamente clasificó los datos de una forma

Al clasificar se generaron demasiadas categorías. un humano no distingue más de 7 (+-2) categorías. ver https://github.com/d3/d3-scale-chromatic

El wms publicado en https://qgiscloud.com/heilyr/Mapa_tematico_class_nube/wms?SERVICE=WMS&REQUEST=GetCapabilities no refleja la simbología que explica en el texto.

El url publicado de qgis2Web no funciona.  (no se ve el mapa, se muestra es el contenido del html)
