### ISSUE TITLE
tarea_3101418

### ISSUE THREAD

**Issue by wilsonpc-geomatica** [dersteppenwolf/cartografia_web#8]
Buenas noches profesor, anexo la dirección de la tarea 1

https://github.com/wilsonpc-geomatica/publicacionweb/blob/master/taller1_3101418.md

**Comment by dersteppenwolf** [comment]
Muy bien. 
Pudo aprovechar las capacidades básicas de qgis en combinación  qgiscloud
para representar la simbología de los temas seleccionados
 
Creo que solo faltó anexar los urls desde donde obtuvo la información y 
explicar el proceso de como generó la capa
" poligonos puntos calientes (Hot Spot) resultantes de una capa de puntos relacionados con eventos de remoción en masa en la ciudad de Bogotá."
